/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Fri Dec 19 11:22:25 BRST 2014
* 
* Call the script: _dummy = this execvm "scripts\boxes\medico.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

  _this additemcargoGlobal ["ACRE_PRC152",100];
  _this additemcargoGlobal ["ACRE_PRC117F",100];
_this additemcargoGlobal ["cse_ab_Kestrel4500",10];
_this additemcargoGlobal ["cse_ab_ATragMX",10];
_this additemcargoGlobal ["cse_HIIDE",10];
   
 
};
