/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Fri Dec 19 11:22:25 BRST 2014
* 
* Call the script: _dummy = this execvm "scripts\boxes\medico.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

  _this additemcargoGlobal ["cse_saline_iv_500",200];
  _this additemcargoGlobal ["cse_atropine",200];
  _this additemcargoGlobal ["cse_personal_aid_kit",50];
  _this additemcargoGlobal ["cse_chestseal",200];
  _this additemcargoGlobal ["cse_epinephrine",200];
  _this additemcargoGlobal ["cse_plasma_iv_250",200];

  _this additemcargoGlobal ["cse_saline_iv",200];
  _this additemcargoGlobal ["cse_blood_iv_250",200];

  _this additemcargoGlobal ["cse_bandage_basic",200];
  _this additemcargoGlobal ["cse_blood_iv",200];
  _this additemcargoGlobal ["cse_surgical_kit",10];
  _this additemcargoGlobal ["cse_packing_bandage",200];
  _this additemcargoGlobal ["cse_quikclot",200];


  _this additemcargoGlobal ["cse_plasma_iv_500",200];
  _this additemcargoGlobal ["cse_bandageElastic",200];
  _this additemcargoGlobal ["cse_tourniquet",200];
  _this additemcargoGlobal ["cse_splint",200];
  _this additemcargoGlobal ["cse_saline_iv_250",200];
  _this additemcargoGlobal ["cse_itemBodyBag",200];
  _this additemcargoGlobal ["cse_blood_iv_500",200];
  _this additemcargoGlobal ["cse_liquidSkin",200];
  _this additemcargoGlobal ["cse_morphine",200];
};
